### ISSUE TITLE
How to use the new BXX and EEX effects?

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#115]
Hello, 

I was wondering how we can use those new effects in NT or is the update only to read already existing commands of .xm files made in other trackers?

Thanks.

**Comment by exelotl** [comment]
Hey, sadly there's no UI for it yet (well, there is an experimental UI that got disabled because it was unfinished / not user friendly). So for the time being any new/improved effect commands are only for improving compatibility with songs made outside of NT.

I have been brainstorming some ideas for how to make a good UI for it, but not ready to share yet. It is the number one feature that I feel NT is lacking so I hope I find time for it soon (or someone else does and it's well designed) :)
